version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: bookstore-web/Dockerfile
#    environment:
#      - BILLING_BASE_URL=${BILLING_BASE_URL}
#      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - "8080:8080"
      - "8000:8000"
    depends_on:
      intershop:
        condition: service_healthy
      redis-app:
        condition: service_healthy
    networks:
      - shop-net
  billing:
    build:
      context: .
      dockerfile: bookstore-billing/Dockerfile
    ports:
      - "8081:8080"
      - "8001:8000"
    depends_on:
      intershop:
        condition: service_healthy
    networks:
      - shop-net
  intershop:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: bookstore
      POSTGRES_USER: baseadm
      POSTGRES_PASSWORD: basepass
      POSTGRES_INITDB_ARGS: "--encoding=UTF8"
    volumes:
      # Сохранение данных между перезапусками
      - postgres_data:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d/init-script.sql:/docker-entrypoint-initdb.d/init-script.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "baseadm", "-d", "bookstore"]
      interval: 1s
      timeout: 5s
      retries: 10
    networks:
      - shop-net
  adminer:
    image: adminer
    restart: always
    depends_on:
      intershop:
        condition: service_healthy
    ports:
      - 8082:8080
    networks:
      - shop-net
  redis-app:
    image: redis:7.4.2
    restart: always
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 1s
      timeout: 3s
      retries: 5
    ports:
      - 6379:6379
    networks:
      - shop-net
    command: [ "redis-server", "--requirepass", "swordfish" ]
networks:
  shop-net:
    driver: bridge
volumes:
  postgres_data: