version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:8080"
      - "8000:8000"
    depends_on:
      intershop:
        condition: service_healthy
    networks:
      - shop-net
  intershop:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: bookstore
      POSTGRES_USER: baseadm
      POSTGRES_PASSWORD: basepass
      POSTGRES_INITDB_ARGS: "--encoding=UTF8"
    volumes:
      # Сохранение данных между перезапусками
      - postgres_data:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d/init-script.sql:/docker-entrypoint-initdb.d/init-script.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "baseadm", "-d", "bookstore"]
      interval: 1s
      timeout: 5s
      retries: 10
    networks:
      - shop-net
  adminer:
    image: adminer
    restart: always
    depends_on:
      intershop:
        condition: service_healthy
    ports:
      - 8082:8080
    networks:
      - shop-net
networks:
  shop-net:
    driver: bridge
volumes:
  postgres_data: