spring:
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    enabled: true
    default-schema: storedata
    url: jdbc:postgresql://intershop:5432/bookstore
    user: baseadm
    password: basepass
  webflux:
    locale: ru_RU
    charset: UTF-8
  application:
    name: store
  r2dbc:
    url: r2dbc:postgresql://intershop:5432/bookstore   # URL подключения к базе данных
    username: baseadm                              # Имя пользователя базы данных
    password: basepass                          # Пароль пользователя
    pool:
      enabled: true                               # Включение пула соединений
      initial-size: 5                             # Начальное количество соединений в пуле
      max-size: 10                                # Максимальное количество соединений
      max-idle-time: 30s                          # Время бездействия соединения перед закрытием
      max-life-time: 10m                          # Максимальное время жизни соединения
      validation-query: SELECT 1                  # SQL-запрос для проверки работоспособности соединения
  datasource:
    init: never
    schema: storedata
  data:
    redis:
      host: redis-app
      port: 6379
      password: swordfish