spring:
  webflux:
    locale: ru_RU
    charset: UTF-8
  application:
    name: store
  r2dbc:
    url: r2dbc:postgresql://intershop:5432/bookstore   # URL подключения к базе данных
    username: baseadm                              # Имя пользователя базы данных
    password: basepass                          # Пароль пользователя
    pool:
      enabled: true                               # Включение пула соединений
      initial-size: 10                            # Начальное количество соединений в пуле
      max-size: 50                                # Максимальное количество соединений
      max-idle-time: 30s                          # Время бездействия соединения перед закрытием
      max-life-time: 10m                          # Максимальное время жизни соединения
      validation-query: SELECT 1                  # SQL-запрос для проверки работоспособности соединения
  datasource:
    init: never
    schema: storedata