spring:
  profiles:
    active: dev
  application:
      name: store
image:
  upload:
    dir: ./uploads/images
    resource: "file:uploads/"
  static:
    resource: classpath:/static/
server:
  reactive:
    session:
      timeout: 4m