DO $$
BEGIN
   IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'baseadm') THEN
      CREATE ROLE baseadm WITH LOGIN PASSWORD 'basepass';
   END IF;
END
$$;

-- Создание базы данных (запускать отдельно, так как нельзя в транзакции)
DO $$
BEGIN
   IF NOT EXISTS (SELECT FROM pg_database WHERE datname = 'store') THEN
      CREATE DATABASE store WITH OWNER baseadm;
   END IF;
END
$$;


-- Создание схемы и назначение владельца
CREATE SCHEMA IF NOT EXISTS storedata AUTHORIZATION baseadm;
ALTER SCHEMA storedata OWNER TO baseadm;

-- Устанавливаем схему по умолчанию
SET search_path TO storedata;

-- Создание таблицы orders
CREATE TABLE IF NOT EXISTS orders (
    order_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comment VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

--CREATE TABLE IF NOT EXISTS products (
--    product_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--    item_id BIGINT,  -- Теперь item_id не обязателен
--    title VARCHAR(255) NOT NULL,
--    item_description TEXT NOT NULL,
--    image_url VARCHAR(255),
--    price DECIMAL(10,2),
--    quantity_available BIGINT,
--    FOREIGN KEY (item_id) REFERENCES items(item_id) ON DELETE SET NULL  -- Если item удален, item_id в product станет NULL
--);
--
---- Создание таблицы items (с обязательным product_id)
--CREATE TABLE IF NOT EXISTS items (
--    item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--    order_id BIGINT NOT NULL,
--    quantity BIGINT,
--    product_id BIGINT NOT NULL,  -- Обязательная ссылка на product
--    FOREIGN KEY (order_id) REFERENCES orders(order_id) ON DELETE CASCADE,
--    FOREIGN KEY (product_id) REFERENCES products(product_id)
--);

-- Создание таблицы items
CREATE TABLE IF NOT EXISTS items (
    item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    quantity BIGINT,
    FOREIGN KEY (order_id) REFERENCES orders(order_id) ON DELETE CASCADE
);

-- Создание таблицы products
CREATE TABLE IF NOT EXISTS products (
    product_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id BIGINT UNIQUE NOT NULL,
    title VARCHAR(255) NOT NULL,
    item_description TEXT NOT NULL,
    image_url VARCHAR(255),
    price DECIMAL(10,2),
    quantity_available BIGINT,
    FOREIGN KEY (item_id) REFERENCES items(item_id)
);